### PR TITLE
Update Thrift

### PR DESCRIPTION
**Pull request by johallar**
# Merge Checklist
## :wrench: Issue(s) fixed:
- [ ] Author referenced issue(s) fixed by this PR:
- [ ] Fixes #0

## :smoking: Smoke Test
- [ ] Works in chrome
- [ ] Works in firefox
- [ ] Works in safari
- [ ] Works in ie edge
- [ ] Works in ie 11

## :ship: Merge
- [ ] author crafted PR's title into release-worthy commit message.

### CODE REVIEW

**Comment by mapd-bot-os** [comment]
Tests failed

**Comment by mapd-bot-os** [comment]
Tests passed

**Comment by mapd-bot-os** [comment]
Tests failed

**Comment by mapd-bot-os** [comment]
Tests failed

**Comment by mapd-bot-os** [comment]
Tests failed

**Comment by israelvicars** [comment]
Admin merged

**Pull request merged**
